version: 1
update_configs:
- package_manager: "java:maven"
  directory: "/"
  update_schedule: "monthly"

  default_reviewers:
    - "warden"
    - "olamy"

  ignored_updates:
    - match:
        dependency_name: "org.jenkins-ci.main:jenkins-core"
    - match:
        dependency_name: "org.jenkins-ci.main:jenkins-war"
    - match:
        dependency_name: "org.jenkins-ci.main:jenkins-bom"
    - match:
        dependency_name: "slf4j-api"
    - match:
        dependency_name: "log4j-over-slf4j"
    - match:
        dependency_name: "jcl-over-slf4j"
    - match:
        dependency_name: "slf4j-jdk14"

